name: CI
on:
  push:
    branches: [main, develop]
    paths: ["src/**", "tests/**", ".github/workflows/**"]
  pull_request:
    branches: [main, develop]
    paths: ["src/**", "tests/**", ".github/workflows/**"]
  workflow_dispatch:

jobs:
  CI_black-flake8-pytest:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        # os: [macos-latest]
        python-version: [3.8, 3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # MacOS
      - name: Setup Conda(Mamba) Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,bioconda,defaults
          channel-priority: true

      - name: Install requirements on MacOS
        run: |
          conda install circos

      - name: Check Circos installation
        run: |
          circos -modules
          circos -h
